доделал index.html
htmlacademy-htmlcss/1916729-sedona-34 pull request #2
Opened 2022-05-23 09:18 UTC by maruh605

2022-05-23 19:27 UTC, Zakamsky requested changes
Все очень добротно, я вижу что ты постарался, в принципе все замечания не критичные, я бы даже принял если бы гостиницы были на месте.

жду с нетерпением полную верстку.

2022-05-23 19:27 UTC, Zakamsky commented on catalog.html
> +            </form>
За форму прямо респект!

2022-05-23 19:27 UTC, Zakamsky commented on catalog.html
> +        </a>
href куда то убежал у нас в свободное плавание =)
(я однажды так сделал в боевом проекте 😇)

2022-05-23 19:27 UTC, Zakamsky commented on catalog.html
> +            </select>
ммм... а вот селект вне формы расстраивает вселенское равновесие...
Я бы предложил либо обернуть его в форму, но ей тогда нужна и кнопка сабмита... 
или сделать эту выпадашку ссылками внутри [details](https://developer.mozilla.org/ru/docs/Web/HTML/Element/details)

2022-05-23 19:27 UTC, Zakamsky commented on catalog.html
> +
как по твоему работают эти элементы? мы куда то переходим когда по ним кликаем?
Если да то все ок.
если мы предполагаем что скрипты будут менять классы и перестраивать стили, то не очень ок...

2022-05-23 19:27 UTC, Zakamsky commented on catalog.html
> +    <section class="newsletter">
а где гостинницы? =(

2022-05-23 19:27 UTC, Zakamsky commented on catalog.html
> +    </footer>
Почти идеально, но на какие части делит футер эта секция?
кажется что она просто лишняя....

2022-05-23 19:27 UTC, Zakamsky commented on index.html
> +            <span class="advantage-number">&#8210; №1 &#8210;</span>
Эти черточки, это точно не контент. Я бы может и номер сделал стилевым счетчиком, а уж черточки точно лучше стилями рисовать....

2022-05-23 19:27 UTC, Zakamsky commented on index.html
> +          </li>
а это точно отдельный пункт списка? больше похоже на иллюстрацию к пункту про мост дьявола.
по сути пункты 1 и 2 одинаковые и отличаются от остальных немного, но еще первый от второго тем что там есть вложенный список подпунктов.

2022-05-24 14:30 UTC, maruh605 commented on catalog.html
> +
тут в обучении говорили что они будут прогружать новую страницу с новым отображением, а не менять отображение на текущей, поэтому ссылками

2022-05-25 11:26 UTC, Zakamsky approved these changes
Отличный вопрос, хорошее исполнение, слегка подкачала табуляция...
Аппрув! выберешь нужную сортировку и офрмишь отступы к следующей главе.

2022-05-25 11:26 UTC, Zakamsky commented on catalog.html
> +              </details>  -->
Здорово что ты сделал оба варинта, оба хороши и самодостаточны.
Финальный выбор должен опираться на несколько фактов - то как выполняется фронт (какой то фрэймворк джс или просто статика), как ожидает бэк получить данные.

В нашем случае все очень просто - ничего этого нет, и мы впадаем в зависимость от скриптов - если они сломаются то пользователь не сможет отправить форму т.к. кнопка скрыта...
Еще очень важный момент дизайн - если выпадабщий список должен быть стилизован - мы не смождем стилизовать нативный селект, а подключить бибилиоткеу кастомного селекта нам не позволят критерии.

Получается что в нашем случае несколько больше плюсов набирает исполнение в виде ссылок.

2022-05-25 11:26 UTC, Zakamsky commented on catalog.html
> +                    </a>
и тут я не понял что куда вложено...

2022-05-25 11:26 UTC, merged

2022-05-25 11:49 UTC, maruh605 commented on catalog.html
> +              </details>  -->
да я немного изучил этот момент и немного представлю  с чем придется столкнутьс в стилизации селектов, поэтому остановлюсь на ссылках

2022-05-25 11:55 UTC, maruh605 commented on catalog.html
> +                    </a>
я немного не понял, списки плохо составлены или табуляция плохая?